---
Style/GlobalVars:
  AllowedVariables: [ $logger, $settings, $git_repo, $tmpdir ]
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 20

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/RedundantSelf:
  Exclude:
    - lib/domain.rb
