---
AllCops:
  TargetRubyVersion: 2.3

Style/GlobalVars:
  AllowedVariables: [ $logger, $settings, $git_repo, $tmpdir ]
Style/StringLiterals:
  Enabled: false
Metrics/LineLength:
  Max: 120
  Exclude:
    - miq_flow.gemspec
Metrics/MethodLength:
  Max: 50
Metrics/AbcSize:
  Max: 20
  Exclude:
    # mixin_config tends to overshoot, but is 
    # still easily readable
    - lib/miq_flow/mixin_config.rb

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space
Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Style/ClassCheck:
  EnforcedStyle: kind_of?

Style/RedundantSelf:
  Exclude:
    - lib/miq_flow/domain.rb
Metrics/BlockLength:
  Exclude:
    - spec/**
    - miq_flow.gemspec
