language: ruby
sudo: required
services:
  - docker
matrix:
  include:
    - name: "Gaprindashvili"
      rvm: 2.3
      env: TAG=latest-gaprindashvili
    - name: "Hammer"
      rvm: 2.4
      env: TAG=hammer-1-rc1
    - name: "Hammer + Integration"
      rvm: 2.4
      env: TAG=hammer-1-rc1 SUITE=integration

before_install:
  - script/prepare_manageiq.sh
  - echo "\$git_url = 'https://github.com/ThomasBuchinger/automate-example.git'" > custom.rb
  - echo "\$default_opts[:log_level] = Logger::DEBUG" >> custom.rb
  - bundle install
script:
  - bundle exec ./bin/cli.rb list
  - bundle exec ./bin/cli.rb inspect feature-1-f1
  - bundle exec ./bin/cli.rb deploy feature-1-f1 --provider docker
  - ./script/verify_import.sh
  - bundle exec rake travis
