language: ruby
sudo: required
services:
  - docker
rvm:
  - 2.3 # Gaprindashvili
  - 2.4 # Hammer
env:
  - TAG=hammer-1-rc1
  - TAG=latest-gaprindashvili
matrix:
  exclude:
    - rvm: 2.4
      env: TAG=latest-gaprindashvili
    - rvm: 2.3
      env: TAG=hammer-1-rc1

before_install:
  - docker pull "manageiq/manageiq:$TAG"
  - script/prepare_manageiq.sh
  - echo '$git_url = "https://github.com/ThomasBuchinger/automate-example.git"' > custom.rb
script:
  - bundle install
  - cat custom.rb
  - bundle exec ./bin/cli.rb list
  - bundle exec ./bin/cli.rb inspect feature-1-f1
  - bundle exec ./bin/cli.rb deploy feature-1-f1 --provider docker
  - ./script/verify_import.sh
  - bundle exec rake travis
