language: ruby
sudo: required
services:
  - docker
matrix:
  include:
    - name: "Gaprindashvili"
      rvm: 2.3
      env: TAG=latest-gaprindashvili
    - name: "Hammer"
      rvm: 2.4
      env: TAG=latest-hammer
    - name: "Ivanchuk (master)"
      rvm: 2.5
      env: TAG=latest
    - name: "Hammer + Integration"
      rvm: 2.4
      env: TAG=latest-hammer SUITE=integration

before_install:
  - script/prepare_manageiq.sh
  - ruby -ryaml -e "c={'log_level'=>'debug', 'git'=>{'url'=>'https://github.com/ThomasBuchinger/automate-example'}}; puts c.to_yaml" > config.yaml
script:
  - bundle check # ManageIQ Container/Appliance needs to satisfy all dependencies
  - rake install:local
  - miq-flow deploy feature-1-f1 --provider docker
  - ./script/verify_import.sh
  - bundle install --with development
  - bundle exec rake travis
