---
# Set logging level
# If set to no_log, no log output will be generated
# Default: info
# Possible values: debug, info, warn, error, fatal, no_log
# log_level: info

# git:
  # Configures a remote git repository as source
  # The repository will be (re)cloned with every invocation
  # Please note, that only HTTPS URLs are allowed on ManageIQ Appliances
  # url: "https://github.com/ThomasBuchinger/automate-example"

  # Configures a local repository as source
  # A local repository may be used if the repository is large or
  # has to be access via SSH
  # path: "/path/to/your/automate-repository"


  #  Specify credentials for the repository.
  #  NOTE: only HTTP Authenication is supported
  #  user: someone
  #  pashsword: <TOKEN>

  # Branch naming scheme
  # This configures the naming scheme for your git branches (if you use one)
  # and how MiqFlow derives a name for the domains imported from that branch.
  # The default configuration matches: TYPE-NAME-optional-description 
  # 
  # characters used to separate part of yu naming convention
  # separators: [ '-', '/' ]
  # index of the NAME part in your naming convention (starts with 0)
  # index: 1

# miq:
  # url: https://localhost/api
  # user: admin
  # password: smartvm

# Clear the temporay working directory after we are finished
# Disabling it, is only useful for debugging
# Default: yes
# Possible Values: yes, no
# clear_tmp: yes

# Sets the working directory
#   auto: generates a new temporary directory. Sets clear_tmp to yes
#   PATH: use existing directory. Sets clear_tmp to no
# Possible values: PATH, auto
# workdir: 'auto'
